### ISSUE TITLE
[Model Certification] - TS0601-motion

### ISSUE THREAD

**Issue by marktn** [zigbeefordomoticz/z4d-certified-devices#82]
Hello,

The motion sensor is certified, only the battery is 200%

If I search a little further about the Tuya devices and the battery status, it seems that it should work. Can you take a look at this?
https://www.zigbee2mqtt.io/devices/TS0203.html
https://www.zigbee2mqtt.io/devices/ZTH01_ZTH02.html
https://www.zigbee2mqtt.io/devices/ZG-227Z.html

**Comment by marktn** [comment]
[export(3).json](https://github.com/user-attachments/files/17738034/export.3.json)

Attached. With all sensors the battery status is not working, thet stay at 100% (door,temp, motion and a switch)
Maybe you can find something with the links i have sent.

**Comment by pipiche38** [comment]
As you can see in the links, the battery is reported by the device. And when I look to the export.json for TS0203 for example, those devices didn't report since a long time.
Unfortunatly as I said, that is not a plugin issue, it is more the devices not sending those informations (and the plugin cannot get them as it is a sleeping device)
